#!/bin/bash

# Couleur violette et gras pour les titres
PURPLE_BOLD='\033[1;35m'
NC='\033[0m' # No Color

# Fonction pour afficher les commandes de gestion de fichiers
afficher_commandes() {
    echo -e "\n\n                  ${PURPLE_BOLD}Commandes de gestion de fichiers :${NC}\n"
    echo "                  ----------------------------------\n"
    echo -e "  ${PURPLE_BOLD}1. Ouvrir un fichier Python avec nano :${NC}"
    echo "       nano fichier.py\n"
    echo -e "  ${PURPLE_BOLD}2. Ouvrir un fichier avec notepad (Windows) :${NC}"
    echo "       notepad fichier.py\n"
    echo -e "  ${PURPLE_BOLD}3. Couper un fichier :${NC}"
    echo "       mv fichier.txt /chemin/destination/\n"
    echo -e "  ${PURPLE_BOLD}4. Copier un fichier :${NC}"
    echo "       cp fichier.txt /chemin/destination/\n"
    echo -e "  ${PURPLE_BOLD}5. Coller (déplacer) un fichier :${NC}"
    echo "       mv /chemin/source/fichier.txt /chemin/destination/\n"
    echo -e "  ${PURPLE_BOLD}6. Lister les fichiers dans le répertoire courant :${NC}"
    echo "       ls\n"
    echo -e "  ${PURPLE_BOLD}7. Afficher le contenu d'un fichier :${NC}"
    echo "       cat fichier.txt\n"
    echo -e "  ${PURPLE_BOLD}8. Supprimer un fichier :${NC}"
    echo "       rm fichier.txt\n"
    echo -e "  ${PURPLE_BOLD}9. Supprimer un répertoire et son contenu :${NC}"
    echo "       rm -r repertoire/\n"
    echo -e "  ${PURPLE_BOLD}10. Créer un répertoire :${NC}"
    echo "       mkdir nouveau_repertoire\n"
    echo -e "  ${PURPLE_BOLD}11. Changer les permissions d'un fichier :${NC}"
    echo "       chmod 755 fichier.sh\n"
    echo -e "  ${PURPLE_BOLD}12. Afficher les informations détaillées sur un fichier :${NC}"
    echo "       ls -l fichier.txt\n"
    echo -e "  ${PURPLE_BOLD}13. Renommer un fichier :${NC}"
    echo "       mv ancien_nom.txt nouveau_nom.txt\n"
    echo -e "  ${PURPLE_BOLD}14. Compresser un fichier avec gzip :${NC}"
    echo "       gzip fichier.txt\n"
    echo -e "  ${PURPLE_BOLD}15. Décompresser un fichier avec gunzip :${NC}"
    echo "       gunzip fichier.txt.gz\n"
    echo -e "  ${PURPLE_BOLD}16. Compresser un répertoire avec tar :${NC}"
    echo "       tar -czvf archive.tar.gz repertoire/\n"
    echo -e "  ${PURPLE_BOLD}17. Décompresser un fichier tar.gz :${NC}"
    echo "       tar -xzvf archive.tar.gz\n"
    echo -e "  ${PURPLE_BOLD}18. Afficher les 10 premières lignes d'un fichier :${NC}"
    echo "       head fichier.txt\n"
    echo -e "  ${PURPLE_BOLD}19. Afficher les 10 dernières lignes d'un fichier :${NC}"
    echo "       tail fichier.txt\n"
    echo -e "  ${PURPLE_BOLD}20. Chercher du texte dans un fichier :${NC}"
    echo "       grep 'texte' fichier.txt\n"
    echo -e "  ${PURPLE_BOLD}21. Compter le nombre de lignes dans un fichier :${NC}"
    echo "       wc -l fichier.txt\n"
    echo -e "  ${PURPLE_BOLD}22. Comparer deux fichiers :${NC}"
    echo "       diff fichier1.txt fichier2.txt\n"
    echo -e "  ${PURPLE_BOLD}23. Afficher l'espace disque utilisé :${NC}"
    echo "       du -sh repertoire/\n"
    echo -e "  ${PURPLE_BOLD}24. Afficher l'espace disque disponible :${NC}"
    echo "       df -h\n"
    echo -e "  ${PURPLE_BOLD}25. Créer un lien symbolique :${NC}"
    echo "       ln -s /chemin/original /chemin/lien\n"
    echo -e "  ${PURPLE_BOLD}26. Changer le propriétaire d'un fichier :${NC}"
    echo "       chown utilisateur:groupe fichier.txt\n"
    echo -e "  ${PURPLE_BOLD}27. Afficher les processus en cours :${NC}"
    echo "       ps aux\n"
    echo -e "  ${PURPLE_BOLD}28. Tuer un processus :${NC}"
    echo "       kill PID\n"
    echo -e "  ${PURPLE_BOLD}29. Afficher l'historique des commandes :${NC}"
    echo "       history\n"
    echo -e "  ${PURPLE_BOLD}30. Vider le contenu d'un fichier :${NC}"
    echo "       > fichier.txt\n"
}

# Appel de la fonction pour afficher les commandes
afficher_commandes

